export enum iStrings {
    FILL_EMPTY_FIELDS = 'Fill out the required fields!',
    SEND_JOB_INVITE = 'Job Invite',
    ACCEPT_JOB_PROPOSAL = 'Accept Proposal',
    REJECT_JOB_PROPOSAL = 'Reject Proposal',
    SUBMIT_JOB_BID = 'Submit Bid',
    WORKSHOP_BOOKED = 'Workshop Booked',
    JOB_COMPLETED = 'Job Completed',
    JOB_PAID = 'Job paid',
    JOB_REJECTED = 'Job rejected',
    INVITED_TO_AGENCY = 'Invited to agency',
    REMOVE_FROM_HUB = 'Hub removal',
    WORKSHOP_RATED = 'Workshop rated',
    VERIFIED_EXPERT = 'Verified expert',
    NON_VERIFIED_EXPERT = 'Non Verified expert',
    HUB_JOIN_REJECTION = 'Hub join rejection',
    HUB_JOIN_ACCEPTANCE = 'Hub join accepted',
    HUB_LEFT = 'Hub left',
    MILESTONE_COMPLETED = 'Milestone completed',
    MILESTONE_PAID = 'Milestone paid',
    MILESTONE_REVERTED = 'Milestone reverted',
    BECAME_HUB_MEMBER = 'You are accepted to become a Member of the Hub',
}